# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1ef27dd9727ba65027f87009ba0b118503506225c336454b82dad8ea70f37082deb1e27774e3123d935b63442286d52918a4326d7b3a9439e891a5c53712874

test:
  secret_key_base: 7971800b308ecbbbab26f478d2a651f554aa9db210606e62d8f6be47de5604abf2d03ab81b0237a10c74052e29b7192ff42e348390b8ec8968991dc5487d161a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
